"use strict";
/* Autogenerated file. Do not edit manually. */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CreditAbi__factory = void 0;
var CreditAbi__factory_1 = require("./factories/CreditAbi__factory");
Object.defineProperty(exports, "CreditAbi__factory", { enumerable: true, get: function () { return CreditAbi__factory_1.CreditAbi__factory; } });
//# sourceMappingURL=index.js.map