/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.48.1
  Forc version: 0.40.1
  Fuel-Core version: 0.19.0
*/

export type { CreditAbi } from './CreditAbi';

export { CreditAbi__factory } from './factories/CreditAbi__factory';
